In [1]:
#@title
%%capture
!rm -rf *
!gdown 19b7ixRt9TU3Kb7r8NwiJ9UaK7Z34-9eH -O e03_ok.zip
!cd /content
!unzip e03_ok.zip
!pip install git+https://github.com/grading/gradememaybe.git

from IPython.display import YouTubeVideo
from gofer import ok

# 1 Upload do Arquivo

Use o espaço abaixo para fazer o upload do arquivo para o ambiente do Google Colab. Para isso você pode usar o comando `gdown` (lembre-se de colocar o sinal de exclamação `!` para chamar comandos na linha de comando, fora do Python).

In [ ]:
from google.colab import files
import io

!rm Iris.csv
!gdown https://drive.google.com/file/d/1d3NbjXro_BfnYpFm66ETBfe7ubAZPAoL/edit

arquivo = files.upload()

rm: cannot remove 'Iris.csv': No such file or directory
/usr/local/lib/python3.10/dist-packages/gdown/parse_url.py:35: UserWarning: You specified a Google Drive link that is not the correct link to download a file. You might want to try `--fuzzy` option or the following url: https://drive.google.com/uc?id=None
  warnings.warn(
Downloading...
From: https://drive.google.com/file/d/1d3NbjXro_BfnYpFm66ETBfe7ubAZPAoL/edit
To: /content/edit
76.1kB [00:00, 38.7MB/s]


Saving Iris.csv to Iris.csv


In [ ]:
ok.check('e03_1.py')

# 2 Leitura do Arquivo

Escreva um laço que leia todas as linhas do arquivo, criando uma lista numa variável de nome 'd0', onde cada elemento da lista é uma string que corresponde a uma linha do arquivo.

In [ ]:
# ERRO INESPERADO

f = io.BytesIO(arquivo['Iris.csv'])
d0 = []
read_list = f.readlines()
f.seek(0)

for lines in read_list:
  s = lines.decode()     # retira o '\n' que adicionava uma linha em branco a mais
  i, sl, sw, pl, pw, sp = s.split(',')
  d0.append(s)

 # print(s)
print(d0)

['Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species\n', '1,5.1,3.5,1.4,0.2,Iris-setosa\n', '2,4.9,3.0,1.4,0.2,Iris-setosa\n', '3,4.7,3.2,1.3,0.2,Iris-setosa\n', '4,4.6,3.1,1.5,0.2,Iris-setosa\n', '5,5.0,3.6,1.4,0.2,Iris-setosa\n', '6,5.4,3.9,1.7,0.4,Iris-setosa\n', '7,4.6,3.4,1.4,0.3,Iris-setosa\n', '8,5.0,3.4,1.5,0.2,Iris-setosa\n', '9,4.4,2.9,1.4,0.2,Iris-setosa\n', '10,4.9,3.1,1.5,0.1,Iris-setosa\n', '11,5.4,3.7,1.5,0.2,Iris-setosa\n', '12,4.8,3.4,1.6,0.2,Iris-setosa\n', '13,4.8,3.0,1.4,0.1,Iris-setosa\n', '14,4.3,3.0,1.1,0.1,Iris-setosa\n', '15,5.8,4.0,1.2,0.2,Iris-setosa\n', '16,5.7,4.4,1.5,0.4,Iris-setosa\n', '17,5.4,3.9,1.3,0.4,Iris-setosa\n', '18,5.1,3.5,1.4,0.3,Iris-setosa\n', '19,5.7,3.8,1.7,0.3,Iris-setosa\n', '20,5.1,3.8,1.5,0.3,Iris-setosa\n', '21,5.4,3.4,1.7,0.2,Iris-setosa\n', '22,5.1,3.7,1.5,0.4,Iris-setosa\n', '23,4.6,3.6,1.0,0.2,Iris-setosa\n', '24,5.1,3.3,1.7,0.5,Iris-setosa\n', '25,4.8,3.4,1.9,0.2,Iris-setosa\n', '26,5.0,3.0,1.6,0.2,Iris-setosa\n', '2

In [ ]:
ok.check('e03_2.py')

# 3 Remoção de Cabeçalho e Contagem de Linhas

Utilizando a mesma variável `d0`, agora remova o cabeçalho (que deve ser o primeiro elemento da lista), e conte as linhas de dados. Grave o total de linhas numa variável de nome `total`.

In [ ]:
f = io.BytesIO(arquivo['Iris.csv'])
d0 = []
read_list = f.readlines()
f.seek(0)
total = 0

for lines in read_list[1:]:
  s = lines.decode()[:-1]     # retira o '\n' que adicionava uma linha em branco a mais
  d0.append(s)
  i, sl, sw, pl, pw, sp = s.split(',')
 # print(s)
  total += 1
print(d0)
print(total)

['1,5.1,3.5,1.4,0.2,Iris-setosa', '2,4.9,3.0,1.4,0.2,Iris-setosa', '3,4.7,3.2,1.3,0.2,Iris-setosa', '4,4.6,3.1,1.5,0.2,Iris-setosa', '5,5.0,3.6,1.4,0.2,Iris-setosa', '6,5.4,3.9,1.7,0.4,Iris-setosa', '7,4.6,3.4,1.4,0.3,Iris-setosa', '8,5.0,3.4,1.5,0.2,Iris-setosa', '9,4.4,2.9,1.4,0.2,Iris-setosa', '10,4.9,3.1,1.5,0.1,Iris-setosa', '11,5.4,3.7,1.5,0.2,Iris-setosa', '12,4.8,3.4,1.6,0.2,Iris-setosa', '13,4.8,3.0,1.4,0.1,Iris-setosa', '14,4.3,3.0,1.1,0.1,Iris-setosa', '15,5.8,4.0,1.2,0.2,Iris-setosa', '16,5.7,4.4,1.5,0.4,Iris-setosa', '17,5.4,3.9,1.3,0.4,Iris-setosa', '18,5.1,3.5,1.4,0.3,Iris-setosa', '19,5.7,3.8,1.7,0.3,Iris-setosa', '20,5.1,3.8,1.5,0.3,Iris-setosa', '21,5.4,3.4,1.7,0.2,Iris-setosa', '22,5.1,3.7,1.5,0.4,Iris-setosa', '23,4.6,3.6,1.0,0.2,Iris-setosa', '24,5.1,3.3,1.7,0.5,Iris-setosa', '25,4.8,3.4,1.9,0.2,Iris-setosa', '26,5.0,3.0,1.6,0.2,Iris-setosa', '27,5.0,3.4,1.6,0.4,Iris-setosa', '28,5.2,3.5,1.5,0.2,Iris-setosa', '29,5.2,3.4,1.4,0.2,Iris-setosa', '30,4.7,3.2,1.6,0.2,Ir

In [ ]:
ok.check('e03_3.py')

# 4 Remoção de Novas Linhas

Crie uma nova lista numa variável de nome `d1` onde cada elemento de `d1` corresponda à versão do mesmo elemento em `d0`, removendo o caractere de nova linha `\n` que aparece ao final de cada item. Assegure-se de que cada elemento da lista `d1` seja uma string simples (dependendo como você fez o upload, pode acontecer dos elementos estarem codificados, então decodifique caso necessário).

In [ ]:
f = io.BytesIO(arquivo['Iris.csv'])
d0 = []
d1 = []
read_list = f.readlines()
f.seek(0)


for lines in read_list[1:]:
  d0.append(s)
  s = lines.decode()[:-1]     # retira o '\n' que adicionava uma linha em branco a mais
  d1.append(s)
  i, sl, sw, pl, pw, sp = s.split(',')
 # print(s)

print(d1)




['1,5.1,3.5,1.4,0.2,Iris-setosa', '2,4.9,3.0,1.4,0.2,Iris-setosa', '3,4.7,3.2,1.3,0.2,Iris-setosa', '4,4.6,3.1,1.5,0.2,Iris-setosa', '5,5.0,3.6,1.4,0.2,Iris-setosa', '6,5.4,3.9,1.7,0.4,Iris-setosa', '7,4.6,3.4,1.4,0.3,Iris-setosa', '8,5.0,3.4,1.5,0.2,Iris-setosa', '9,4.4,2.9,1.4,0.2,Iris-setosa', '10,4.9,3.1,1.5,0.1,Iris-setosa', '11,5.4,3.7,1.5,0.2,Iris-setosa', '12,4.8,3.4,1.6,0.2,Iris-setosa', '13,4.8,3.0,1.4,0.1,Iris-setosa', '14,4.3,3.0,1.1,0.1,Iris-setosa', '15,5.8,4.0,1.2,0.2,Iris-setosa', '16,5.7,4.4,1.5,0.4,Iris-setosa', '17,5.4,3.9,1.3,0.4,Iris-setosa', '18,5.1,3.5,1.4,0.3,Iris-setosa', '19,5.7,3.8,1.7,0.3,Iris-setosa', '20,5.1,3.8,1.5,0.3,Iris-setosa', '21,5.4,3.4,1.7,0.2,Iris-setosa', '22,5.1,3.7,1.5,0.4,Iris-setosa', '23,4.6,3.6,1.0,0.2,Iris-setosa', '24,5.1,3.3,1.7,0.5,Iris-setosa', '25,4.8,3.4,1.9,0.2,Iris-setosa', '26,5.0,3.0,1.6,0.2,Iris-setosa', '27,5.0,3.4,1.6,0.4,Iris-setosa', '28,5.2,3.5,1.5,0.2,Iris-setosa', '29,5.2,3.4,1.4,0.2,Iris-setosa', '30,4.7,3.2,1.6,0.2,Ir

In [ ]:
ok.check('e03_4.py')

# 5 Separação por Vírgulas

Crie uma nova lista em uma variável de nome `d2` onde cada elemento dessa lista seja uma sublista contendo as strings correspondentes a cada dado da string original, usando a vírgula como separador.

Por exemplo, transforme isso:

`'14,4.3,3.0,1.1,0.1,Iris-setosa'`

nisso:

`['14', '4.3', '3.0', '1.1', '0.1', 'Iris-setosa']`

Faça isso para todos elementos, na mesma ordem da lista original, gravando o resultado em `d2`.


In [ ]:
f = io.BytesIO(arquivo['Iris.csv'])
read_list = f.readlines()
f.seek(0)
d2 = []
import numpy as np

x = np.zeros((len(lines)- 1, 4))

for i, lines in enumerate(read_list[1:]):
  list1 = []
  s = lines.decode()[:-1]     # retira o '\n' que adicionava uma linha em branco a mais
  i, sl, sw, pl, pw, sp = s.split(',')
#  i = int(i)
 # sl = float(sl)
  #sw = float(sw)
  #pl = float(pl)
  #pw = float(pw)
#  x[i:] = np.array([sl, sw, pl, pw])
  list1.extend([i, sl, sw, pl, pw, sp])
  d2.append(list1)

print(d2)



[['1', '5.1', '3.5', '1.4', '0.2', 'Iris-setosa'], ['2', '4.9', '3.0', '1.4', '0.2', 'Iris-setosa'], ['3', '4.7', '3.2', '1.3', '0.2', 'Iris-setosa'], ['4', '4.6', '3.1', '1.5', '0.2', 'Iris-setosa'], ['5', '5.0', '3.6', '1.4', '0.2', 'Iris-setosa'], ['6', '5.4', '3.9', '1.7', '0.4', 'Iris-setosa'], ['7', '4.6', '3.4', '1.4', '0.3', 'Iris-setosa'], ['8', '5.0', '3.4', '1.5', '0.2', 'Iris-setosa'], ['9', '4.4', '2.9', '1.4', '0.2', 'Iris-setosa'], ['10', '4.9', '3.1', '1.5', '0.1', 'Iris-setosa'], ['11', '5.4', '3.7', '1.5', '0.2', 'Iris-setosa'], ['12', '4.8', '3.4', '1.6', '0.2', 'Iris-setosa'], ['13', '4.8', '3.0', '1.4', '0.1', 'Iris-setosa'], ['14', '4.3', '3.0', '1.1', '0.1', 'Iris-setosa'], ['15', '5.8', '4.0', '1.2', '0.2', 'Iris-setosa'], ['16', '5.7', '4.4', '1.5', '0.4', 'Iris-setosa'], ['17', '5.4', '3.9', '1.3', '0.4', 'Iris-setosa'], ['18', '5.1', '3.5', '1.4', '0.3', 'Iris-setosa'], ['19', '5.7', '3.8', '1.7', '0.3', 'Iris-setosa'], ['20', '5.1', '3.8', '1.5', '0.3', 'Iri

In [ ]:
ok.check('e03_5.py')

# 6 Entradas de Treinamento

Crie uma matriz no formato `array` do NumPy, numa variável de nome `d3`, contendo todos os dados da segunda, terceira, quarta e quinta colunas de `d2` transformados para o formato ponto flutuante (convertendo de string para número). Não inclua nem a primeira coluna (que é o id), nem a última coluna nessa conversão. Essa será a matriz de entradas.

In [ ]:
f = io.BytesIO(arquivo['Iris.csv'])
read_list = f.readlines()
f.seek(0)
d2 = []
d3 = []
import numpy as np

x = np.zeros((len(lines)- 1, 4))

for i, lines in enumerate(read_list[1:]):
  list1 = []
  list2 = []
  s = lines.decode()[:-1]     # retira o '\n' que adicionava uma linha em branco a mais
  i, sl, sw, pl, pw, sp = s.split(',')
  i = int(i)
  x[i:] = np.array([sl, sw, pl, pw])
  list1.extend([i, sl, sw, pl, pw, sp])
  d2.append(list1)
  sl = float(sl)
  sw = float(sw)
  pl = float(pl)
  pw = float(pw)
  list2.extend([sl, sw, pl, pw])
  d3.append(list2)

print(d3)



[[5.1, 3.5, 1.4, 0.2], [4.9, 3.0, 1.4, 0.2], [4.7, 3.2, 1.3, 0.2], [4.6, 3.1, 1.5, 0.2], [5.0, 3.6, 1.4, 0.2], [5.4, 3.9, 1.7, 0.4], [4.6, 3.4, 1.4, 0.3], [5.0, 3.4, 1.5, 0.2], [4.4, 2.9, 1.4, 0.2], [4.9, 3.1, 1.5, 0.1], [5.4, 3.7, 1.5, 0.2], [4.8, 3.4, 1.6, 0.2], [4.8, 3.0, 1.4, 0.1], [4.3, 3.0, 1.1, 0.1], [5.8, 4.0, 1.2, 0.2], [5.7, 4.4, 1.5, 0.4], [5.4, 3.9, 1.3, 0.4], [5.1, 3.5, 1.4, 0.3], [5.7, 3.8, 1.7, 0.3], [5.1, 3.8, 1.5, 0.3], [5.4, 3.4, 1.7, 0.2], [5.1, 3.7, 1.5, 0.4], [4.6, 3.6, 1.0, 0.2], [5.1, 3.3, 1.7, 0.5], [4.8, 3.4, 1.9, 0.2], [5.0, 3.0, 1.6, 0.2], [5.0, 3.4, 1.6, 0.4], [5.2, 3.5, 1.5, 0.2], [5.2, 3.4, 1.4, 0.2], [4.7, 3.2, 1.6, 0.2], [4.8, 3.1, 1.6, 0.2], [5.4, 3.4, 1.5, 0.4], [5.2, 4.1, 1.5, 0.1], [5.5, 4.2, 1.4, 0.2], [4.9, 3.1, 1.5, 0.1], [5.0, 3.2, 1.2, 0.2], [5.5, 3.5, 1.3, 0.2], [4.9, 3.1, 1.5, 0.1], [4.4, 3.0, 1.3, 0.2], [5.1, 3.4, 1.5, 0.2], [5.0, 3.5, 1.3, 0.3], [4.5, 2.3, 1.3, 0.3], [4.4, 3.2, 1.3, 0.2], [5.0, 3.5, 1.6, 0.6], [5.1, 3.8, 1.9, 0.4], [4.8, 3.0

In [ ]:
ok.check('e03_6.py')

# 7 Saídas Desejadas

Crie um `array` do NumPy para as saídas desejadas, no formado _one-hot_. Para isso utilize as strings da última coluna de `d2`, verificando qual espécie de planta se refere cada string:

 `'Iris-setosa'` $\rightarrow$ `[1.0, 0.0, 0.0]`

 `'Iris-versicolor'` $\rightarrow$ `[0.0, 1.0, 0.0]`

 `'Iris-virginica'` $\rightarrow$ `[0.0, 0.0, 1.0]`

 Grave o resultado em um `array` do NumPy de nome `d4`, com o mesmo número de linhas de `d3`, onde cada linha de `d4` corresponde ao vetor _one-hot_ da saída desejada da respectiva linha de entradas de `d4`.

In [ ]:
import io
import numpy as np

# Suponha que 'arquivo' seja o objeto contendo o arquivo 'Iris.csv'

f = io.BytesIO(arquivo['Iris.csv'])
read_list = f.readlines()
f.seek(0)
d2 = []
d3 = []

# Corrigindo a variável 'lines' para 'read_list'
x = np.zeros((len(read_list) - 1, 4))
d4 = np.zeros((len(read_list) - 1, 3))
cat = np.array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'])

for i, lines in enumerate(read_list[1:]):
    list1 = []
    list2 = []
    s = lines.decode()[:-1]  # Remove o caractere '\n' no final da linha
    _, sl, sw, pl, pw, sp = s.split(',')
    i = int(i)
    x[i:] = np.array([sl, sw, pl, pw]).astype(float)
    d4[i:] = (cat == sp).astype(float)
    list1.extend([i, sl, sw, pl, pw, sp])
    d2.append(list1)
    sl = float(sl)
    sw = float(sw)
    pl = float(pl)
    pw = float(pw)
    list2.extend([sl, sw, pl, pw])
    d3.append(list2)

print(d3, len(d3))
print(d4, len(d4))


[[5.1, 3.5, 1.4, 0.2], [4.9, 3.0, 1.4, 0.2], [4.7, 3.2, 1.3, 0.2], [4.6, 3.1, 1.5, 0.2], [5.0, 3.6, 1.4, 0.2], [5.4, 3.9, 1.7, 0.4], [4.6, 3.4, 1.4, 0.3], [5.0, 3.4, 1.5, 0.2], [4.4, 2.9, 1.4, 0.2], [4.9, 3.1, 1.5, 0.1], [5.4, 3.7, 1.5, 0.2], [4.8, 3.4, 1.6, 0.2], [4.8, 3.0, 1.4, 0.1], [4.3, 3.0, 1.1, 0.1], [5.8, 4.0, 1.2, 0.2], [5.7, 4.4, 1.5, 0.4], [5.4, 3.9, 1.3, 0.4], [5.1, 3.5, 1.4, 0.3], [5.7, 3.8, 1.7, 0.3], [5.1, 3.8, 1.5, 0.3], [5.4, 3.4, 1.7, 0.2], [5.1, 3.7, 1.5, 0.4], [4.6, 3.6, 1.0, 0.2], [5.1, 3.3, 1.7, 0.5], [4.8, 3.4, 1.9, 0.2], [5.0, 3.0, 1.6, 0.2], [5.0, 3.4, 1.6, 0.4], [5.2, 3.5, 1.5, 0.2], [5.2, 3.4, 1.4, 0.2], [4.7, 3.2, 1.6, 0.2], [4.8, 3.1, 1.6, 0.2], [5.4, 3.4, 1.5, 0.4], [5.2, 4.1, 1.5, 0.1], [5.5, 4.2, 1.4, 0.2], [4.9, 3.1, 1.5, 0.1], [5.0, 3.2, 1.2, 0.2], [5.5, 3.5, 1.3, 0.2], [4.9, 3.1, 1.5, 0.1], [4.4, 3.0, 1.3, 0.2], [5.1, 3.4, 1.5, 0.2], [5.0, 3.5, 1.3, 0.3], [4.5, 2.3, 1.3, 0.3], [4.4, 3.2, 1.3, 0.2], [5.0, 3.5, 1.6, 0.6], [5.1, 3.8, 1.9, 0.4], [4.8, 3.0

In [ ]:
ok.check('e03_7.py')

# 8 Normalização das Entradas

Encontre o valor máximo e mínimo para cada uma das quatro colunas da matriz de entradas. Normalize os valores das entradas no intervalo entre zero e um, salvando o resultado em um `array` do NumPy de nome `d5`.

In [ ]:
max = [0, 0, 0, 0]
min = [10, 10, 10, 10]
d5 = []

for lines in d3:
  for i, columns in enumerate(lines):
      if columns >= max[i]:
        max[i] = columns
      if columns <= min[i]:
        min[i] = columns

print(min)
print(max)

# LISTA NORMALIZADA:

for lines in d3:
  list_norma = []
  for i, columns in enumerate(lines):
    normal = (columns - min[i]) / (max[i] - min[i])
    list_norma.append(normal)
  d5.append(list_norma)

d5 = np.array(d5)
print(d5)


[4.3, 2.0, 1.0, 0.1]
[7.9, 4.4, 6.9, 2.5]
[[0.22222222 0.625      0.06779661 0.04166667]
 [0.16666667 0.41666667 0.06779661 0.04166667]
 [0.11111111 0.5        0.05084746 0.04166667]
 [0.08333333 0.45833333 0.08474576 0.04166667]
 [0.19444444 0.66666667 0.06779661 0.04166667]
 [0.30555556 0.79166667 0.11864407 0.125     ]
 [0.08333333 0.58333333 0.06779661 0.08333333]
 [0.19444444 0.58333333 0.08474576 0.04166667]
 [0.02777778 0.375      0.06779661 0.04166667]
 [0.16666667 0.45833333 0.08474576 0.        ]
 [0.30555556 0.70833333 0.08474576 0.04166667]
 [0.13888889 0.58333333 0.10169492 0.04166667]
 [0.13888889 0.41666667 0.06779661 0.        ]
 [0.         0.41666667 0.01694915 0.        ]
 [0.41666667 0.83333333 0.03389831 0.04166667]
 [0.38888889 1.         0.08474576 0.125     ]
 [0.30555556 0.79166667 0.05084746 0.125     ]
 [0.22222222 0.625      0.06779661 0.08333333]
 [0.38888889 0.75       0.11864407 0.08333333]
 [0.22222222 0.75       0.08474576 0.08333333]
 [0.30555556 0.583

In [ ]:
ok.check('e03_8.py')

# 9 Embaralhamento dos Dados

Misture as linhas dos dados dos valores de entradas de treinamento contidos em `d5` de forma aleatória. Faça o mesmo com as linhas das saídas desejadas em `d4`, de forma a manter a correspondência entre ambos. Chame a `array` resultante de dados de treinamento embaralhado de `x` e a `array` correspondente de saídas desejadas de `y`.

In [ ]:
d4_list = d4.tolist()
d5_list = d5.tolist()

y = []
x = []

lista_indices = [x for x in range(len(d4_list))]
lista_indices = np.array(lista_indices)
np.random.shuffle(lista_indices)

print(lista_indices)

for i, j in enumerate(lista_indices):
  print(i, j)
  y.append(d4_list[j])
  x.append(d5_list[j])
  print(x[i], y[i])

x = np.array(x)
y = np.array(y)
print(y)
print(x)
#print(d5)


############# ERRADOOOOOOOOOOOOOOOOOOOOOOOOO DE ACORDO COM O CHECK

[ 17 128  19  96 135  87  58  64 125   1 105  34  23 100  66  37 123 142
 126  97  26 101   9  86  15 113  78  92  91 127   4 143 137  67 148  47
  20  13  88  31  51 108  69  22 144  89 140  25 149  83  14 122  10  99
  90  61  42  57 106  44  76  36  49 145  77  81 131  60  16  95 104  18
 109  30 102  32  46   6  54 115   5  70  41   3 132  75  93  65 138  56
  84  59  40  45  71  52 139  50  63 141 114  74 129 124  98  24   2 136
 133  72  11  38  68 111  33  35  62   0 118 116 146 120  85  79   7 110
  48 119  80 107 103 117  21  55 147  53 134  82  39  27  94 121 112  73
   8  28  29 130  43  12]
0 17
[0.22222222222222213, 0.6249999999999999, 0.06779661016949151, 0.08333333333333333] [1.0, 0.0, 0.0]
1 128
[0.5833333333333334, 0.3333333333333332, 0.7796610169491525, 0.8333333333333334] [0.0, 0.0, 1.0]
2 19
[0.22222222222222213, 0.7499999999999998, 0.0847457627118644, 0.08333333333333333] [1.0, 0.0, 0.0]
3 96
[0.38888888888888895, 0.3749999999999999, 0.5423728813559322, 0.5] [0.0, 

In [ ]:
ok.check('e03_9.py')

# 10 Separação de Dados de Treinamento e Validação

Separe os pares de dados de treinamento e validação nas proporções 90%/10%, respectivamente. Chame a entrada e saída desejada dos pares de treinamento de `x_train` e `y_train`, e use os nomes `x_test` e `y_test` para os dados de validação. Os dados de validação devem corresponder às linhas finais dos pares de `array` originais `x` e `y`.

In [ ]:
# CASO DER ERRO, EXECUTAR CÉLULA ACIMA E DEPOIS ESTA EM SEGUIDA

x_test = []
y_test = []
x_train = []
y_train = []
x = x.tolist()
y = y.tolist()

for i in range(len(x)):
  if i < (0.9*len(x)):
    x_train.append(x[i])
    y_train.append(y[i])

  else:
    x_test.append(x[i])
    y_test.append(y[i])

print(x_train == x[:135])

x_train = np.array(x_train)
y_train = np.array(y_train)
x_test = np.array(x_test)
y_test = np.array(y_test)

print(x_test, len(x_test))
print(y_test, len(y_test))
print(x_train, len(x_train))
print(y_train, len(y_train))


True
[[0.33333333 0.125      0.50847458 0.5       ]
 [0.5        0.25       0.77966102 0.54166667]
 [0.41666667 0.29166667 0.49152542 0.45833333]
 [0.22222222 0.58333333 0.08474576 0.04166667]
 [0.25       0.625      0.08474576 0.04166667]
 [0.36111111 0.29166667 0.54237288 0.5       ]
 [0.36111111 0.33333333 0.66101695 0.79166667]
 [0.69444444 0.41666667 0.76271186 0.83333333]
 [0.5        0.33333333 0.62711864 0.45833333]
 [0.02777778 0.375      0.06779661 0.04166667]
 [0.25       0.58333333 0.06779661 0.04166667]
 [0.11111111 0.5        0.10169492 0.04166667]
 [0.86111111 0.33333333 0.86440678 0.75      ]
 [0.19444444 0.625      0.10169492 0.20833333]
 [0.13888889 0.41666667 0.06779661 0.        ]] 15
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]] 15
[[0.22222222 0.625      0.06779661 0.08333333]
 [0.58333333 0.33333333 0.77966102 0.83333333]
 [0.2222

In [ ]:
ok.check('e03_10.py')